services:
  csohelper-postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    volumes:
      - ./storage/pgdata/:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"

  csohelper-redis:
    image: redis:7
    restart: always
    environment:
      TZ: ${TZ}
    volumes:
      - ./storage/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
#    ports:
#      - "6379:6379"

  csohelper-bot-api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_LOCAL: ${TELEGRAM_LOCAL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./storage/tgapi/:/var/lib/telegram-bot-api
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://csohelper-bot-api:8081/bot${TELEGRAM_BOT_TOKEN}/getMe || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 3s

  csohelper-nginx:
    image: nginx:latest
    restart: always
    environment:
      TZ: ${TZ}
    volumes:
      - ./storage/tgapi/:/var/lib/telegram-bot-api:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      csohelper-bot-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://csohelper-nginx:8082/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 3s
#    ports:
#      - "8082:8082"

  csohelper-bot:
    build: bot
    restart: always
    environment:
      TZ: ${TZ}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./storage/bot/:/app/storage/
    depends_on:
      csohelper-postgres:
        condition: service_healthy
      csohelper-redis:
        condition: service_healthy
      csohelper-nginx:
        condition: service_healthy
